version: '2'
services:
    base-java:
        build: 
            context: splice_machine_docker/base_java/
        image: base-java:latest
    base-mvn:
        build: 
            context: splice_machine_docker/base_mvn/
        image: base-mvn:latest
        depends_on: 
           - "base-java"
    base-protobuf:
        build: 
            context: splice_machine_docker/base_protobuf/
        image: base-protobuf:latest
        depends_on: 
           - "base-mvn"
    splice-app:
        build: 
            context: .
            dockerfile: splice_machine_docker/splice_app/Dockerfile
        depends_on: 
            - "base-protobuf"
        volumes:
            - ./:spliceengine
        image: splice-app:latest
